CREATE TABLE IF NOT EXISTS "jobs" (
	"id" uuid PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"guid" text NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"required_skills" text[] NOT NULL,
	"nice_to_have_skills" text[],
	"workplace_type" text NOT NULL,
	"working_time" text NOT NULL,
	"experience_level" text NOT NULL,
	"employment_types" jsonb NOT NULL,
	"category_id" text NOT NULL,
	"category_name" text,
	"multilocation" jsonb NOT NULL,
	"city" text NOT NULL,
	"street" text NOT NULL,
	"latitude" text NOT NULL,
	"longitude" text NOT NULL,
	"remote_interview" text NOT NULL,
	"company_name" text NOT NULL,
	"company_logo_thumb_url" text NOT NULL,
	"published_at" text NOT NULL,
	"open_to_hire_ukrainians" text NOT NULL,
	"languages" text[] NOT NULL,
	"plan" text NOT NULL
);
